# Generated by Django 6.0.1 on 2026-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimate",
            name="gst",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="total",
        ),
        migrations.AddField(
            model_name="estimate",
            name="cement_bags",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="estimate",
            name="sand_tons",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="estimate",
            name="total_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="estimate",
            name="total_paint_sqm",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="estimate",
            name="total_tiles_sqm",
            field=models.FloatField(default=0),
        ),
    ]
