# Generated by Django 6.0.1 on 2026-01-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimates", "0002_remove_estimate_gst_remove_estimate_subtotal_and_more"),
        ("projects", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiles_sqm", models.FloatField(default=0)),
                ("paint_sqm", models.FloatField(default=0)),
                ("cement_bags", models.IntegerField(default=0)),
                ("sand_tons", models.FloatField(default=0)),
                ("cost", models.FloatField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_estimates",
                        to="projects.project",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
