# Generated by Django 6.0.1 on 2026-02-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimates", "0003_roomestimate"),
        ("projects", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="EstimateLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Civil", "Civil Work"),
                            ("Interior", "Interior Work"),
                            ("Electrical", "Electrical Work"),
                            ("Plumbing", "Plumbing Work"),
                            ("Painting", "Painting Work"),
                            ("Flooring", "Flooring Work"),
                        ],
                        max_length=50,
                    ),
                ),
                ("item_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.FloatField(help_text="Quantity of work")),
                (
                    "unit",
                    models.CharField(help_text="sqm, sqft, nos, etc.", max_length=20),
                ),
                ("rate", models.FloatField(help_text="Rate per unit in ₹")),
                (
                    "amount",
                    models.FloatField(help_text="Total amount (quantity × rate)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="estimates.estimate",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Room this item belongs to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Civil", "Civil Work"),
                            ("Interior", "Interior Work"),
                            ("Electrical", "Electrical Work"),
                            ("Plumbing", "Plumbing Work"),
                            ("Painting", "Painting Work"),
                            ("Flooring", "Flooring Work"),
                        ],
                        max_length=50,
                    ),
                ),
                ("item_name", models.CharField(max_length=150)),
                ("unit", models.CharField(max_length=20)),
                ("rate", models.FloatField(help_text="Rate per unit in ₹")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific location for this rate (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "item_name"],
                "unique_together": {
                    ("category", "item_name", "location", "effective_from")
                },
            },
        ),
        migrations.CreateModel(
            name="WorkProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_quantity", models.FloatField()),
                ("completed_quantity", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="estimates.estimatelineitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_progress",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
