# Generated by Django 6.0.1 on 2026-01-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("Civil + Interior", "Civil + Interior"),
                            ("Civil Only", "Civil Only"),
                            ("Interior Only", "Interior Only"),
                        ],
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("builtup_area", models.FloatField(help_text="Area in sqft")),
                ("status", models.CharField(default="Planning", max_length=50)),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
