# Generated by Django 6.0.1 on 2026-03-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="builtup_area",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Built-up area in sq ft (for residential)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("RESIDENTIAL", "Residential"),
                    ("RETAIL", "Retail Display"),
                    ("COMMERCIAL", "Commercial"),
                ],
                default="RESIDENTIAL",
                help_text="Select project type",
                max_length=20,
            ),
        ),
    ]
