# Generated by Django 6.0.1 on 2026-03-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_options_remove_project_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
