# Generated by Django 6.0.1 on 2026-01-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planupload",
            name="scale",
            field=models.CharField(
                choices=[("mm", "Millimeter"), ("m", "Meter")],
                default="mm",
                max_length=10,
            ),
        ),
    ]
