# Generated by Django 6.0.1 on 2026-02-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0002_planupload_scale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planupload",
            name="file_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
