# Generated by Django 6.0.1 on 2026-02-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_alter_planupload_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planupload",
            name="file_type",
            field=models.CharField(default="unknown", max_length=20),
        ),
    ]
