# Generated by Django 6.0.1 on 2026-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0004_alter_planupload_file_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planupload",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Plan Upload",
                "verbose_name_plural": "Plan Uploads",
            },
        ),
        migrations.RenameField(
            model_name="planupload",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="planupload",
            name="processed",
        ),
        migrations.AddField(
            model_name="planupload",
            name="processing_result",
            field=models.JSONField(
                blank=True, help_text="Processing results or error details", null=True
            ),
        ),
        migrations.AddField(
            model_name="planupload",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                help_text="Current processing status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="planupload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="planupload",
            name="file",
            field=models.FileField(
                help_text="Upload DXF, DWG, or PDF file", upload_to="uploads/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="planupload",
            name="file_type",
            field=models.CharField(
                choices=[("dxf", "DXF File"), ("dwg", "DWG File"), ("pdf", "PDF File")],
                default="dxf",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="planupload",
            name="scale",
            field=models.CharField(
                choices=[
                    ("mm", "Millimeters"),
                    ("cm", "Centimeters"),
                    ("m", "Meters"),
                    ("in", "Inches"),
                    ("ft", "Feet"),
                ],
                default="mm",
                help_text="Scale unit used in the file",
                max_length=10,
            ),
        ),
    ]
