# Generated by Django 6.0.1 on 2026-03-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_alter_project_options_remove_project_scope_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specification", models.CharField(blank=True, max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("sqft", "Square Feet"),
                            ("meter", "Meter"),
                            ("piece", "Piece"),
                            ("unit", "Unit"),
                            ("hour", "Hour"),
                            ("liter", "Liter"),
                            ("kg", "Kilogram"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate in ₹", max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dxf_layer_names",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated layer names (e.g., MDF_18MM, MDF18, PANEL_MDF)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "ordering": ["category", "name", "specification"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("SHEET", "Sheet Materials"),
                            ("LIGHTING", "Lighting"),
                            ("HARDWARE", "Hardware"),
                            ("LABOR", "Labor & Fabrication"),
                            ("FINISHING", "Finishing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Material Category",
                "verbose_name_plural": "Material Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("PANEL", "Panel"),
                            ("SHELF", "Shelf"),
                            ("LIGHTING", "Lighting"),
                            ("HARDWARE", "Hardware"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                (
                    "dimensions",
                    models.JSONField(
                        blank=True,
                        help_text="Store length, width, height if applicable",
                        null=True,
                    ),
                ),
                ("layer_name", models.CharField(blank=True, max_length=100)),
                ("auto_detected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retail_components",
                        to="projects.project",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="components",
                        to="retail_materials.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
                "ordering": ["component_type", "description"],
            },
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="retail_materials.materialcategory",
            ),
        ),
        migrations.CreateModel(
            name="RetailEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "validity_days",
                    models.IntegerField(default=30, help_text="Quote validity in days"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retail_estimate",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retail Estimate",
                "verbose_name_plural": "Retail Estimates",
            },
        ),
    ]
